mikrotik-backup: WIP

diff --git a/mikrotik-backup/rootfs/usr/bin/do_backup b/mikrotik-backup/rootfs/usr/bin/do_backup
--- a/mikrotik-backup/rootfs/usr/bin/do_backup
+++ b/mikrotik-backup/rootfs/usr/bin/do_backup
@@ -12,7 +12,17 @@ git -C "/data/repo" pull
 ssh_host_args="$(bashio::config ssh_host_args)"
 
 echo "$ssh_host_args" | while read -r host_args; do
-  echo "ARGS: $host_args"
+  echo -n "HOST: $host_args"
+
+  # shellcheck disable=SC2086
+  ident="$(_ssh $host_args 'put [/system identity print as-value]')"
+  if [[ ! "$ident" =~ ^name=(.*)$ ]]; then
+      echo "Invalid identity output: '$ident'" >&2
+      exit 1
+  fi
+  ident="${BASH_REMATCH[1]}"
+
+  echo "$ident"
 done
 
 exit 0
